# Generated by Django 3.2.3 on 2022-01-13 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fledit', '0015_alter_todomodel_rootid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='rootid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_root', to='fledit.rootmodel', verbose_name='行程データ'),
        ),
    ]
